name: Build sing-box tuic only

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: arm
            goarm: "7"
    
    steps:
      - uses: actions/checkout@v4
        with:
          repository: SagerNet/sing-box
          ref: v1.2.7

      - uses: actions/setup-go@v5
        with:
          go-version: '1.19'

      - name: Build TUIC only
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
        run: |
          mkdir -p dist
          go build \
            -trimpath \
            -ldflags "-s -w -buildid=" \
            -tags "with_quic" \
            -o dist/sing-box-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm }} \
            ./cmd/sing-box

      - uses: actions/upload-artifact@v4
        with:
          name: sing-box-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm }}
          path: dist/sing-box-*
